# Use root/example as user/password credentials

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27020:27017" # listening on port 27017 inside the container, on 27020 on the outside
    #restart: always

  #mongo-express:
  #image: mongo-express
  #restart: always
  #ports:
  #- 27020:27017
